INSERT INTO cartas (nombre, ataque, defensa, poder, tipo, imagen, descripcion) VALUES
("Wildheart Warden", 7, 10, 6, "defensa", "1_card.jpg", "Un guerrero de la naturaleza que canaliza la fuerza de las bestias salvajes. Su corazón late al mismo ritmo que los espíritus del bosque."),
("Infernal Banecaller", 10, 6, 7, "ataque", "2_card.jpg", "Llama a las criaturas del abismo para cazar demonios con el mismo fuego del infierno que los vio nacer."),
("Twilight Seraphim", 6, 5, 8, "poder", "3_card.jpg", "Un ángel oscuro atrapado entre la luz y la sombra. Sus alas llevan el peso de dos mundos enfrentados."),
("Luminary Oracle", 4, 7, 7, "poder", "4_card.jpg", "Portadora de antiguas profecías, capaz de ver todos los futuros posibles y elegir el que conduce a la salvación."),
("Sunforge Valkyrie", 9, 6, 6, "ataque", "5_card.jpg", "Una guerrera bendecida por el sol naciente. Su arma arde con la luz del amanecer, purificando todo a su paso."),
("Nightblood Enchantress", 7, 7, 11, "poder", "6_card.jpg", "Maestra de hechizos prohibidos, tejidos con sangre nocturna y antiguas maldiciones que pocos se atreven a pronunciar."),
("Dreadhorn Ravager", 11, 5, 6, "ataque", "7_card.jpg", "Mitad bestia, mitad demonio, nacido para devastar. Su furia no conoce límites ni alianzas."),
("Frostveil Crusader", 5, 11, 8, "defensa", "8_card.jpg", "Un caballero envuelto en escarcha eterna. Su presencia congela el valor de sus enemigos."),
("Ironhorn Sentinel", 6, 11, 7, "defensa", "9_card.jpg", "Guardián ancestral con la fuerza de un gigante taurino. Inquebrantable incluso ante los dioses."),
("Scarlet Wingcaller", 8, 8, 8, "poder", "10_card.jpg", "Invocadora alada cuyo poder fluye con los vientos carmesí. Sus cánticos hacen temblar al mismísimo cielo."),

("Pyrebound Reaper", 11, 6, 9, "ataque", "17_card.jpg", "Un elemental nacido de la fusión imposible entre hielo y fuego. Su espada ardiente quiebra el aire mientras su cuerpo exhala un frío mortal."),
("Bonewraith Herald", 5, 7, 2, "poder", "18_card.jpg", "Un espectro esquelético que anuncia la llegada de la muerte. Cada batir de sus alas extingue el calor de los vivos."),
("Emberguard Champion", 10, 8, 9, "ataque", "19_card.jpg", "Guardián de los reinos ardientes. Su esfera de energía puede reducir ejércitos enteros a cenizas."),
("Spellforge Minstrel", 7, 6, 10, "poder", "20_card.jpg", "Un trovador arcano capaz de convertir melodías en runas vivas. Su voz puede romper hechizos o tejerlos."),
("Frostdrake Paladin", 8, 11, 11, "defensa", "11_card.jpg", "Un caballero bendecido por los dragones helados. Su lanza canaliza tormentas glaciares."),
("Stormveil Ascendant", 6, 7, 5, "poder", "12_card.jpg", "Encarnación viva de la tormenta. Cada paso despierta relámpagos que obedecen su voluntad."),
("Ashwing Phoenixborn", 11, 6, 8, "ataque", "13_card.jpg", "Criatura renacida del fuego puro. Sus alas pueden incendiar montañas enteras."),
("Ironclad Vindicator", 7, 11, 2, "defensa", "14_card.jpg", "Un guerrero férreo imparable. Su armadura encantada resiste incluso el fuego de dragón."),
("Glacial Wardbreaker", 6, 11, 6, "defensa", "15_card.jpg", "Guardián gélido capaz de congelar cualquier barrera mágica. Su espada divide tanto el hielo como el destino."),
("Shadowblaze Seraph", 5, 9, 6, "poder", "16_card.jpg", "Un ser celestial corrompido por las sombras. Su luz incendiaria quema tanto cuerpos como almas."),

("Doomcaller Lichlord", 7, 6, 10, "poder", "27_card.jpg", "Un nigromante ancestral cuyo espíritu quedó atrapado entre los planos. Su toque extingue tanto la vida como la magia."),
("Sunforge Gladiator", 11, 8, 6, "ataque", "28_card.jpg", "Forjado en batallas eternas, lucha con una fuerza que parece rivalizar con el propio sol."),
("Hellwing Tempstress", 9, 7, 11, "poder", "29_card.jpg", "Una hechicera demoníaca cuyos encantos y llamas arrasan reinos enteros."),
("Stormhorn Warlord", 10, 11, 10, "defensa", "30_card.jpg", "Líder de las tribus azules, su coraje resuena como un trueno que rompe montañas."),
("Veilshroud Spellbinder", 6, 7, 7, "poder", "21_card.jpg", "Su manto oscurece todo a su paso mientras teje runas invisibles que manipulan la realidad."),
("Shadowthorn Reaper", 11, 8, 4, "ataque", "22_card.jpg", "Un asesino oculto en las sombras del bosque eterno. Su guadaña es tan silenciosa como mortal."),
("Astral Gryphon", 8, 10, 10, "poder", "23_card.jpg", "Una bestia celestial que cabalga los vientos cósmicos protegiendo los cielos sagrados."),
("Frostborne Tracker", 7, 11, 9, "defensa", "24_card.jpg", "Cazador implacable cuyos pasos dejan un rastro de escarcha eterna."),
("Nightflare Enchantress", 8, 7, 8, "poder", "25_card.jpg", "Una maga nocturna que controla la luz y la oscuridad como si fueran un solo elemento."),
("Elderwood Guardian", 6, 11, 9, "defensa", "26_card.jpg", "Protector del bosque primigenio. Sus raíces antiguas contienen la sabiduría de mil eras.");
